eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    
spring:
  hibernate:
    generate_statistics: true
    cache: 
      use_second_level_cache: true
      use_query_cache: true
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        

  